### ISSUE TITLE
My Page UI

### ISSUE THREAD

**Issue by TakayasuNasu** [TakayasuNasu/FamousSpotTour#13]
Please make it as similar to Figma UI as possible.
---

> except color of gray at Circle indicator.

<img width="887" alt="ss-mypage" src="https://user-images.githubusercontent.com/6420260/106368357-55bdb780-638c-11eb-8e6c-0d98d752d7b5.png">

**Comment by sangomax** [comment]
I tried to change direction of progress bar and curve in segment button, but I can't.

**Comment by sangomax** [comment]
the size of picture and progress bar, I will do

**Comment by sangomax** [comment]
<img width="1440" alt="Screen Shot 2021-01-30 at 8 31 22 PM" src="https://user-images.githubusercontent.com/72472287/106374712-71986d80-633a-11eb-86f5-56cf5210fa9b.png">
]()

**Comment by sangomax** [comment]
is it good?

**Comment by TakayasuNasu** [comment]
@sangomax 

Thanks Adriano. that's looks so nice.
Also, can you add white circle edges at the picture?

**Comment by sangomax** [comment]
done
<img width="1440" alt="Screen Shot 2021-01-30 at 10 20 51 PM" src="https://user-images.githubusercontent.com/72472287/106376365-89c3b900-6349-11eb-98b8-d4d87ca1f086.png">

**Comment by TakayasuNasu** [comment]
@sangomax 
**Thanks a lot. It's perfect.**
